//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFM_VentaOnline
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class venta_onlineEntities : DbContext
    {
        public venta_onlineEntities()
            : base("name=venta_onlineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<caracteristicas> caracteristicas { get; set; }
        public virtual DbSet<categorias> categorias { get; set; }
        public virtual DbSet<conexiones> conexiones { get; set; }
        public virtual DbSet<marcas> marcas { get; set; }
        public virtual DbSet<multimedia> multimedia { get; set; }
        public virtual DbSet<paises> paises { get; set; }
        public virtual DbSet<perfiles> perfiles { get; set; }
        public virtual DbSet<productos> productos { get; set; }
        public virtual DbSet<productos_caracteristicas> productos_caracteristicas { get; set; }
        public virtual DbSet<productos_categorias> productos_categorias { get; set; }
        public virtual DbSet<productos_multimedia> productos_multimedia { get; set; }
        public virtual DbSet<productos_vendedores> productos_vendedores { get; set; }
        public virtual DbSet<telefonos> telefonos { get; set; }
        public virtual DbSet<tiposAccion> tiposAccion { get; set; }
        public virtual DbSet<tiposMultimedia> tiposMultimedia { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<valoracionesProducto> valoracionesProducto { get; set; }
        public virtual DbSet<valoracionesVendedor> valoracionesVendedor { get; set; }
        public virtual DbSet<vendedores> vendedores { get; set; }
        public virtual DbSet<acciones> acciones { get; set; }
    }
}
