//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFM_VentaOnline
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos_caracteristicas
    {
        public int id { get; set; }
        public int producto { get; set; }
        public int caracteristica { get; set; }
        public string valor { get; set; }
        public string referencia { get; set; }
    
        public virtual caracteristicas caracteristicas { get; set; }
        public virtual productos productos { get; set; }
    }
}
